### ISSUE TITLE
Can not load js file in ng-view an ng-inculde

### ISSUE THREAD

**Issue by ChaosInOrder** [Ben-Yin/Spartan#4]
To get foot js, must go into inspect model. May be resolved by http://stackoverflow.com/questions/12197880/angularjs-how-to-make-angular-load-script-inside-ng-include.
Already tried it but did not work.

**Comment by Ben-Yin** [comment]
Resolve by using directive.

1. include `loadScriptDirective` in `index.html`
2. add dependency in `app.js`
3. use `<load-script type="text/javascript-lazy" src=""></load-script>` to load the JS file
